<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net9.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageVersion>0.6.0</PackageVersion>
        <Authors>snifter</Authors>
        <AssemblyVersion>0.6.0</AssemblyVersion>
        <Title>MRZCodeParser</Title>
        <PackageProjectUrl>https://github.com/snifter/MRZCode.NET</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/snifter/MRZCode.NET.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>MRZ parser for .NET</Description>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>MRZCodeParser.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
